#ifndef SGS_PROTO_H
#define SGS_PROTO_H

enum GAMPROTO
{
	/* GAME CMD */
	GAME_START = 1000,
	
	//add your game cmd
	GAME_OUT_CARD,
	GAME_OUT_CARD_BC,
	GAME_DISCARD,
	GAME_DISCARD_BC,
	GAME_USE_SKILL,
	GAME_USE_SKILL_BC,
	GAME_CANCEL_OUT_CARD,
	GAME_CANCEL_OUT_CARD_BC,
	GAME_PLAY_CARD_END,
	GAME_PLAY_CARD_END_BC,
	GAME_PLAY_CARD_BC,
	GAME_SELECT_CARD,
	GAME_SELECT_CARD_BC,
	GAME_SELECT_HERO,
	GAME_SELECT_HERO_BC,
	GAME_EQUIP,
	GAME_EQUIP_BC,
	GAME_DEAL_BC,
	GAME_GAME_END,
	GAME_DISCARD_UC,
	GAME_CHANGE_BLOOD_BC,
	GAME_CHAT,
	GAME_CHAT_BC,

};

#endif