#include "sgsgameattr.h"
#include "player.h"
#include "room.h"
#include "proto.h"
#include "../jsonproto/jsonproto.h"
#include "../ppacket.h"
#include <list>
#include <map>
#include <iostream>
#include <stdio.h>
#include <string>
#include "cocos2d.h"
#include "ui/CocosGUI.h"
#include "ui\UIWidget.h"
#include "boost.asio.1.0.159/boost/asio.hpp"
#include "../Classes/libs/json/json.h"
#include "../Classes/libs/json/json-forwards.h"